# Generated by Django 6.0 on 2026-02-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_alter_item_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='priority',
        ),
    ]
