# Generated by Django 6.0 on 2026-02-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_remove_item_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='priority',
            field=models.TextField(default='Low'),
        ),
    ]
